### ISSUE TITLE
BarChart not rendering on Firefox.

### ISSUE THREAD

**Issue by miezis** [rma-consulting/react-easy-chart#42]
Everything except bars are being rendered on Firefox. Same chart is being rendered correctly on Chrome.

**Comment by harunhasdal** [comment]
Thanks for reporting this @miezis. I've looked into this. We are using css `height` property instead of svg `height` attribute to set the height of bars in order to be able to animate the bar height with css transitions. 

This doesn't seem to work on firefox. 

I am leaning towards dropping the css transition for now in favour of getting the charts rendering correctly in firefox.
